/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package miterapp.internal;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import miterapp.models.Question;
import miterapp.repositories.QuestionRepository;

/**
 *
 * @author begoingtodev
 */
public class AddQuestion extends javax.swing.JInternalFrame {
    private QuestionRepository questionRepo;
    private ListQuestion listQuestion;
    /**
     * Creates new form AddQuestion
     */
    public AddQuestion() {
        initComponents();
    }
    
    public void setItemRepo(QuestionRepository repo){
        this.questionRepo = repo;
    }
    
    public void setListItem(ListQuestion listItem){
        this.listQuestion = listItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtq1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtq2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtq3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtq4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCorrectAnswer = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbLevel = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        txtq1.setFont(new java.awt.Font("Kantumruy Pro", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Kantumruy Pro", 1, 14)); // NOI18N
        jLabel5.setText("Answer2");

        txtq2.setFont(new java.awt.Font("Kantumruy Pro", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Kantumruy Pro", 1, 14)); // NOI18N
        jLabel6.setText("Answer3");

        txtq3.setFont(new java.awt.Font("Kantumruy Pro", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Kantumruy Pro", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Question");

        jLabel7.setFont(new java.awt.Font("Kantumruy Pro", 1, 14)); // NOI18N
        jLabel7.setText("Answer4");

        jLabel2.setFont(new java.awt.Font("Kantumruy Pro", 1, 14)); // NOI18N
        jLabel2.setText("Level");

        txtq4.setFont(new java.awt.Font("Kantumruy Pro", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Kantumruy Pro", 1, 14)); // NOI18N
        jLabel8.setText("Currect Answer");

        jLabel3.setFont(new java.awt.Font("Kantumruy Pro", 1, 14)); // NOI18N
        jLabel3.setText("Question");

        txtCorrectAnswer.setFont(new java.awt.Font("Kantumruy Pro", 0, 14)); // NOI18N

        txtTitle.setFont(new java.awt.Font("Kantumruy Pro", 0, 14)); // NOI18N

        btnSave.setBackground(new java.awt.Color(153, 255, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Kantumruy Pro", 1, 14)); // NOI18N
        jLabel4.setText("Answer1");

        cbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Intermedate", "Advance" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtq1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtq3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtq2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtq4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(cbLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtq1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtq2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtq3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtq4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(
          this.txtTitle.getText().isBlank() ||
          this.txtq1.getText().isBlank() ||
          this.txtq2.getText().isBlank() ||
          this.txtq3.getText().isBlank() ||
          this.txtq4.getText().isBlank() ||
          this.txtCorrectAnswer.getText().isBlank()
                ){
            JOptionPane.showMessageDialog(rootPane, "Please all input are required.");
            return;
        }
        Question q = new Question();
        q.setId(questionRepo.items.size()+1);
        q.setLevel(this.cbLevel.getSelectedItem().toString());
        q.setTitle(this.txtTitle.getText());
        q.setCorrectAnswer(Integer.valueOf(this.txtCorrectAnswer.getText()));
        List<String> a = new ArrayList<>();
        a.add(this.txtq1.getText());
        a.add(this.txtq2.getText());
        a.add(this.txtq3.getText());
        a.add(this.txtq4.getText());
        q.setAnswers(a);
        this.questionRepo.AddQuestion(q);
        this.listQuestion.addItem(q);
        JOptionPane.showMessageDialog(rootPane, "You have been add successfully");
        this.clearForm();
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void clearForm(){
        this.txtTitle.setText(null);
        this.txtCorrectAnswer.setText(null);
        this.txtq1.setText(null);
        this.txtq2.setText(null);
        this.txtq3.setText(null);
        this.txtq4.setText(null);
        this.cbLevel.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCorrectAnswer;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtq1;
    private javax.swing.JTextField txtq2;
    private javax.swing.JTextField txtq3;
    private javax.swing.JTextField txtq4;
    // End of variables declaration//GEN-END:variables
}
