/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package miterapp.internal;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import miterapp.MainDashboard;
import miterapp.models.Question;
import miterapp.repositories.QuestionRepository;

/**
 *
 * @author begoingtodev
 */
public class ListQuestion extends javax.swing.JInternalFrame {

    private List<Question> items = new ArrayList<>();
    private final DefaultTableModel tbl;
    private MainDashboard mainDashboard;
    private QuestionRepository questionRepo;
    

    /**
     * Creates new form ListQuestion
     */
    public ListQuestion() {
        initComponents();
        this.tbl = (DefaultTableModel) this.tblItem.getModel();
    }

    public void setItems(List<Question> data) {
        this.items = data;
    }

    public void loadDataTable() {
        for (Question item : items) {
            this.addItem(item);
        }
    }
    
    public void setItemRepo(QuestionRepository repo){
        this.questionRepo = repo;
    }
    
    public void setMainDashboard(MainDashboard main){
        this.mainDashboard = main;
    }
    
    public void removeItem(Integer index){
        this.tbl.removeRow(index);
    }

    public void addItem(Question q) {
        tbl.addRow(new Object[]{
            q.getId(),
            q.getTitle(),
            q.getLevel(),
            q.getCorrectAnswer(),
            q.getAnswers().get(0),
            q.getAnswers().get(1),
            q.getAnswers().get(2),
            q.getAnswers().get(3)
        });
    }
    
    public void setUpdateItem(int index, Question q){
        tbl.setValueAt(q.getId(), index, 0);
        tbl.setValueAt(q.getTitle(), index, 1);
        tbl.setValueAt(q.getLevel(), index, 2);
        tbl.setValueAt(q.getCorrectAnswer(), index, 3);
        tbl.setValueAt(q.getAnswers().get(0), index, 4);
        tbl.setValueAt(q.getAnswers().get(1), index, 5);
        tbl.setValueAt(q.getAnswers().get(2), index, 6);
        tbl.setValueAt(q.getAnswers().get(3), index, 7);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Level", "Currect Answer", "Q1", "Q2", "Q3", "Q4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItem.setFocusable(false);
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblItemMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);
        if (tblItem.getColumnModel().getColumnCount() > 0) {
            tblItem.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblItem.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        System.out.println("Closing...");
    }//GEN-LAST:event_formInternalFrameClosed

    private void tblItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMousePressed
        // TODO add your handling code here:
        Integer selectedIndex = this.tblItem.getSelectedRow();
        Question selectedQ = items.get(selectedIndex);
        AddQuestion fq = new AddQuestion();
        fq.setName("updateQuestion");
        fq.setItemRepo(questionRepo);
        fq.setListItem(this);
        fq.setItemToField(selectedQ,selectedIndex);
        mainDashboard.showChild(fq);
    }//GEN-LAST:event_tblItemMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
}
